
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miniblog_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - miniblog

  nginx:
    image: nginx:alpine
    container_name: miniblog_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - miniblog

  mysql:
      image: mysql:8.0
      container_name: miniblog_mysql
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: miniblog
          MYSQL_USER: laravel
          MYSQL_PASSWORD: password
      volumes:
          - mysql_data:/var/lib/mysql
      networks:
          - miniblog
      healthcheck:
          test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "laravel", "-ppassword" ]
          interval: 5s
          timeout: 5s
          retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: miniblog_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - miniblog

volumes:
  mysql_data:

networks:
  miniblog:
    driver: bridge
